<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Item Location</name>
   <tag></tag>
   <elementGuidId>0f7f5286-5138-4395-9bf0-16259df56a66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c3-mainPanel-location</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c3-mainPanel-location']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5945bf5-3c33-4863-9575-2633e9c554ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e836ce0a-c1a4-40b1-b57b-d4657d804176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-overlay-aspect active</value>
      <webElementGuid>106d1122-c1c6-4dd0-896e-43493dbf1f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1a754666-4073-4f71-b9cd-9dcf96f6e999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aspecttitle</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>44e516fd-c117-4d6e-acd4-23508a73801e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4043125f-0f97-4bad-b8fd-cb566e6d76af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>refineOverlay-subPanel</value>
      <webElementGuid>8b4374c8-129a-42a7-9d58-0d71097df573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c3-mainPanel-location</value>
      <webElementGuid>32bdee58-717e-459d-a9cb-a71693382840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Item Location</value>
      <webElementGuid>b7e0f0b5-9248-4895-bd87-b30b80595084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c3-mainPanel-location&quot;)</value>
      <webElementGuid>0c05a88c-975d-4c9e-a007-1c896ea52da2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='c3-mainPanel-location']</value>
      <webElementGuid>2e2d2c19-f31f-405b-8bd0-f82d4478e1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c3-mainPanel']/div[10]</value>
      <webElementGuid>d895473b-3a9e-4d6b-8075-a2f3e351802d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[10]</value>
      <webElementGuid>d40c3097-4c35-48ce-83be-b6780a32cfb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'c3-mainPanel-location' and (text() = 'Item Location' or . = 'Item Location')]</value>
      <webElementGuid>64ad576e-442a-44f7-ba82-043870643cd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
