<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_asia</name>
   <tag></tag>
   <elementGuidId>937ecbc4-8e7a-4bec-89fe-3c7c6bdd603c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c3-subPanel-location_Asia > span.field > span.radio.field__control.rbx.x-refine__single-select-radio > input[name=&quot;location&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='location'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43795129-2ca4-4e3c-8dd1-2bb93d6a9e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>45625a7b-40a2-4c8d-8af3-4d11b2599c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5d53c59e-fd41-4747-a8ef-6fa93705ff24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Asia</value>
      <webElementGuid>432b5bb8-98a8-456f-95bc-3fe50d777594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Asia</value>
      <webElementGuid>b9fa58e4-1708-4fd7-bb09-f9c3c66458cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>9695617b-f3e0-4d2d-8bb9-27284a857805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>59c40a3c-4af0-450e-a08b-de69ede9f622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>36f210ba-8866-423b-b26a-95ba7dc89f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio__control</value>
      <webElementGuid>3eb152d2-5b28-49f6-87ef-757a11c87363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>af7714bf-b243-4725-a62a-ebe189232d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c3-subPanel-location_Asia&quot;)/span[@class=&quot;field&quot;]/span[@class=&quot;radio field__control rbx x-refine__single-select-radio&quot;]/input[@class=&quot;radio__control&quot;]</value>
      <webElementGuid>ad909b58-f362-48a4-94aa-2d67663750c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='location'])[5]</value>
      <webElementGuid>db94e57a-8931-473f-bb69-92a763b2ccf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c3-subPanel-location_Asia']/span/span/input</value>
      <webElementGuid>7d6478c1-7577-4534-a571-4fb811625ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/span/input</value>
      <webElementGuid>0dd9cb54-430b-4ffd-a27e-356ffa2fbd01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'location' and @type = 'radio']</value>
      <webElementGuid>d8c5c5bc-9317-42eb-b537-c43ddde84a8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
