<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_new</name>
   <tag></tag>
   <elementGuidId>6b087973-872c-4d8f-a131-ba56928d103b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c3-subPanel-LH_ItemCondition_New_cbx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c3-subPanel-LH_ItemCondition_New_cbx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0003cc20-b9df-48ad-9144-6562504f7efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69df1619-c4e0-4e53-8d55-88bf5e6c3bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>256da8ea-8972-414a-95dd-43e36ad3ac82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bad6d374-fb94-4b3e-b92a-bc743fce638d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c3-subPanel-LH_ItemCondition_New_cbx</value>
      <webElementGuid>b10b9618-517a-4e1f-9611-3c61be0b59f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>728cdd37-b116-4100-9f8f-a9f74d3b8faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox__control</value>
      <webElementGuid>06705fe5-a208-435a-9517-b98e44f01e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7b4c44aa-2bce-4e99-ba8f-78aaf922adf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c3-subPanel-LH_ItemCondition_New_cbx&quot;)</value>
      <webElementGuid>6541673b-3878-4190-8bee-12a95ca099bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c3-subPanel-LH_ItemCondition_New_cbx']</value>
      <webElementGuid>6d432be7-3b70-48ad-9b33-71ba7d83cbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c3-subPanel-LH_ItemCondition_New']/span/span/input</value>
      <webElementGuid>ea652128-ec48-4630-8aea-596173ac0f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>3595119e-27e1-4ef6-8c41-428e2f9a8e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c3-subPanel-LH_ItemCondition_New_cbx' and @type = 'checkbox']</value>
      <webElementGuid>4858de5a-297d-4c4c-a262-9c454423f055</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
