<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropbar_Category</name>
   <tag></tag>
   <elementGuidId>6117685f-ff72-44e1-9d32-a4110dad1014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gh-shop-a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gh-shop-a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>edc9e6cf-3c5f-4e0c-8b7b-7bcaacb1ac83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gh-shop-a</value>
      <webElementGuid>9d043ef4-bf73-46e1-90eb-f0e7851aacbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b0c07e65-efc1-44d4-a498-f19f5bfbaf97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-control</value>
      <webElementGuid>734436fa-40ea-4c1d-88b2-078e7874c07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>gh-sbc-o</value>
      <webElementGuid>af0b0b23-bba3-4839-ae43-c74cdc917aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Shop by category</value>
      <webElementGuid>12281230-f018-4788-8fa8-9fcc96809532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gh-shop-a&quot;)</value>
      <webElementGuid>c285d132-ab80-4531-abfd-58cc6bc092dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gh-shop-a']</value>
      <webElementGuid>a59f918b-499e-4f75-a672-1c62e32c2187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gh-shop']/button</value>
      <webElementGuid>60e97c88-bd7e-4e40-bb7a-ced521685b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::button[1]</value>
      <webElementGuid>80e79ea5-9121-4718-877d-37c018f52536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop by category'])[2]/preceding::button[1]</value>
      <webElementGuid>76f87840-9f42-4cfc-8c2f-1ae81c2bb2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collectibles &amp; art'])[1]/preceding::button[1]</value>
      <webElementGuid>ca17ffba-b081-4d33-a12b-11866882cd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shop by category']/parent::*</value>
      <webElementGuid>aab98441-6eb7-4344-a917-a8acac961102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6c31a99e-ae61-416e-9e67-732148ade7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'gh-shop-a' and (text() = ' Shop by category' or . = ' Shop by category')]</value>
      <webElementGuid>056d7af5-4139-4bae-ad13-9a77e84b536d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
