<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropbar</name>
   <tag></tag>
   <elementGuidId>2b621005-d7e0-430d-b4d2-8ae8dd837af6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gh-cat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gh-cat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>660c4ce6-bd75-4417-9556-88e2d4525042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select a category for search</value>
      <webElementGuid>145654d9-1c5d-4f30-9288-e5b915dc21fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-sb </value>
      <webElementGuid>d32eaf82-e6fe-45c0-85c2-20c2c6d0f5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cc156f75-1fe6-4d8f-9847-c7ac6fd474a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gh-cat</value>
      <webElementGuid>a18634f8-ff07-43ce-b8dc-6e21a69d253d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_sacat</value>
      <webElementGuid>554fce02-196f-46bf-9514-9f2eaba803ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All CategoriesAntiquesArtBabyBooksBusiness &amp; IndustrialCameras &amp; PhotoCell Phones &amp; AccessoriesClothing, Shoes &amp; AccessoriesCoins &amp; Paper MoneyCollectiblesComputers/Tablets &amp; NetworkingConsumer ElectronicsCraftsDolls &amp; BearsDVDs &amp; MovieseBay MotorsEntertainment MemorabiliaGift Cards &amp; CouponsHealth &amp; BeautyHome &amp; GardenJewelry &amp; WatchesMusicMusical Instruments &amp; GearPet SuppliesPottery &amp; GlassReal EstateSpecialty ServicesSporting GoodsSports Mem, Cards &amp; Fan ShopStampsTickets &amp; ExperiencesToys &amp; HobbiesTravelVideo Games &amp; ConsolesEverything Else</value>
      <webElementGuid>0b4dec18-1864-4de7-8cd0-f55946b914fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gh-cat&quot;)</value>
      <webElementGuid>6213bc61-6e70-486b-902b-2385b5c67e9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gh-cat']</value>
      <webElementGuid>ed977a7d-8ad2-423d-8cb5-08e9cd1b58c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gh-cat-box']/select</value>
      <webElementGuid>6fc7dd86-b35a-4c52-b4b4-c5fc10b95f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your search keyword'])[1]/following::select[1]</value>
      <webElementGuid>4a391815-59c6-4a94-82eb-0eaa281a2c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See all categories'])[1]/following::select[1]</value>
      <webElementGuid>3a3df54a-27d7-4e9d-924d-d4937ee207f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced'])[1]/preceding::select[1]</value>
      <webElementGuid>278b7c84-3525-4afd-bac0-3b3da0d59b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>95ec40e0-b63d-49c2-bc27-bbab7ef02dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gh-cat' and @name = '_sacat' and (text() = 'All CategoriesAntiquesArtBabyBooksBusiness &amp; IndustrialCameras &amp; PhotoCell Phones &amp; AccessoriesClothing, Shoes &amp; AccessoriesCoins &amp; Paper MoneyCollectiblesComputers/Tablets &amp; NetworkingConsumer ElectronicsCraftsDolls &amp; BearsDVDs &amp; MovieseBay MotorsEntertainment MemorabiliaGift Cards &amp; CouponsHealth &amp; BeautyHome &amp; GardenJewelry &amp; WatchesMusicMusical Instruments &amp; GearPet SuppliesPottery &amp; GlassReal EstateSpecialty ServicesSporting GoodsSports Mem, Cards &amp; Fan ShopStampsTickets &amp; ExperiencesToys &amp; HobbiesTravelVideo Games &amp; ConsolesEverything Else' or . = 'All CategoriesAntiquesArtBabyBooksBusiness &amp; IndustrialCameras &amp; PhotoCell Phones &amp; AccessoriesClothing, Shoes &amp; AccessoriesCoins &amp; Paper MoneyCollectiblesComputers/Tablets &amp; NetworkingConsumer ElectronicsCraftsDolls &amp; BearsDVDs &amp; MovieseBay MotorsEntertainment MemorabiliaGift Cards &amp; CouponsHealth &amp; BeautyHome &amp; GardenJewelry &amp; WatchesMusicMusical Instruments &amp; GearPet SuppliesPottery &amp; GlassReal EstateSpecialty ServicesSporting GoodsSports Mem, Cards &amp; Fan ShopStampsTickets &amp; ExperiencesToys &amp; HobbiesTravelVideo Games &amp; ConsolesEverything Else')]</value>
      <webElementGuid>54c6aafd-f1e9-4208-a03d-0fda9505600d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
