<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_first_product</name>
   <tag></tag>
   <elementGuidId>4631ea1f-81b3-42b9-bd7c-858284926e22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item429446b761 > div.s-item__wrapper.clearfix > div.s-item__info.clearfix > a.s-item__link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item429446b761']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>28cf3386-48b6-475e-9219-a39bcc870b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interactions</name>
      <type>Main</type>
      <value>[{&quot;actionKind&quot;:&quot;NAVSRC&quot;,&quot;interaction&quot;:&quot;wwFVrK2vRE0lhQQ0MDFKQk5ZUFY2U1o4VFdXQ1owUUtGM1E0SzY0MDFKQk5ZUFYzRTZUSFlHTThOUkJZNVdZQkoAAAg3NDAwDE5BVlNSQwA=&quot;}]</value>
      <webElementGuid>50667db0-95fc-42e8-8cb6-9ff36fe1d3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f11f0499-220a-4f5a-b56e-1a2925a74bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_sp</name>
      <type>Main</type>
      <value>p2351460.m1686.l7400</value>
      <webElementGuid>2c5d6d6d-6e9d-4565-bff4-697f5c462ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-s-0y04713</name>
      <type>Main</type>
      <value>{&quot;eventFamily&quot;:&quot;LST&quot;,&quot;eventAction&quot;:&quot;ACTN&quot;,&quot;actionKind&quot;:&quot;NAVSRC&quot;,&quot;actionKinds&quot;:[&quot;NAVSRC&quot;],&quot;operationId&quot;:&quot;2351460&quot;,&quot;flushImmediately&quot;:false,&quot;eventProperty&quot;:{&quot;$l&quot;:&quot;320625648676015&quot;}}</value>
      <webElementGuid>3eac6a8b-0684-4026-bf45-f257353ccba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-item__link</value>
      <webElementGuid>504ccd63-058f-46ae-b321-2e79bc0f1c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ebay.com/itm/285955503969?_skw=MacBook&amp;itmmeta=01JBNYPV3E6THYGM8NRBY5WYBJ&amp;hash=item429446b761:g:c7EAAOSwrHNms9th&amp;itmprp=enc%3AAQAJAAAA4HoV3kP08IDx+KZ9MfhVJKmNLUyv1ip+6KrA7SygB6aVPyHk7fBmHIIzpk8%2FK85g39MRAVhdcvw3Zh6NpND4vzP1pROUzvGN+Cx8BIVRcZo1Tgarui283ZEnkX%2FTvhedrUZXcApeoEeKkcOWG+I55zO376YMPccJDqVLehlcpSZZXtgdwfgBCa7%2F3MnUYXZ9R2d5+dpZhN96z1Rp1DE0eWbmBb0mMyDjcKr33+MV72NFjbCME1LlHzVCTyLeChZmqJDGjWucjSPsm+mu2QO6DKDZDtQ9hhDJYWPVFLmpDVsC%7Ctkp%3ABFBM5rHbvt1k</value>
      <webElementGuid>e3511c29-b2ca-4725-b9f9-6cc633163bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EXCELLENT Apple MacBook Air 11 INTEL CORE i5 SSD Mac OSOpens in a new window or tab</value>
      <webElementGuid>56fc2a18-3ccc-4a68-b462-2689e3dd2776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item429446b761&quot;)/div[@class=&quot;s-item__wrapper clearfix&quot;]/div[@class=&quot;s-item__info clearfix&quot;]/a[@class=&quot;s-item__link&quot;]</value>
      <webElementGuid>582af01e-f21d-4cfb-942e-c9d1fef86eda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item429446b761']/div/div[2]/a</value>
      <webElementGuid>80478b25-e02c-4195-bfff-f8ddd6f246cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- apply Screen Size filter'])[5]/following::a[3]</value>
      <webElementGuid>1c534f30-3767-4c13-a8dc-83d30797ee1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- apply Screen Size filter'])[4]/following::a[4]</value>
      <webElementGuid>ede75a46-9ec3-4b79-819c-7a7675cee935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.ebay.com/itm/285955503969?_skw=MacBook&amp;itmmeta=01JBNYPV3E6THYGM8NRBY5WYBJ&amp;hash=item429446b761:g:c7EAAOSwrHNms9th&amp;itmprp=enc%3AAQAJAAAA4HoV3kP08IDx+KZ9MfhVJKmNLUyv1ip+6KrA7SygB6aVPyHk7fBmHIIzpk8%2FK85g39MRAVhdcvw3Zh6NpND4vzP1pROUzvGN+Cx8BIVRcZo1Tgarui283ZEnkX%2FTvhedrUZXcApeoEeKkcOWG+I55zO376YMPccJDqVLehlcpSZZXtgdwfgBCa7%2F3MnUYXZ9R2d5+dpZhN96z1Rp1DE0eWbmBb0mMyDjcKr33+MV72NFjbCME1LlHzVCTyLeChZmqJDGjWucjSPsm+mu2QO6DKDZDtQ9hhDJYWPVFLmpDVsC%7Ctkp%3ABFBM5rHbvt1k')])[2]</value>
      <webElementGuid>4e038f79-d22e-4da2-af99-e4f9b83c524b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div[2]/a</value>
      <webElementGuid>13ee8365-72e7-4df8-ad90-5ae8ead23144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ebay.com/itm/285955503969?_skw=MacBook&amp;itmmeta=01JBNYPV3E6THYGM8NRBY5WYBJ&amp;hash=item429446b761:g:c7EAAOSwrHNms9th&amp;itmprp=enc%3AAQAJAAAA4HoV3kP08IDx+KZ9MfhVJKmNLUyv1ip+6KrA7SygB6aVPyHk7fBmHIIzpk8%2FK85g39MRAVhdcvw3Zh6NpND4vzP1pROUzvGN+Cx8BIVRcZo1Tgarui283ZEnkX%2FTvhedrUZXcApeoEeKkcOWG+I55zO376YMPccJDqVLehlcpSZZXtgdwfgBCa7%2F3MnUYXZ9R2d5+dpZhN96z1Rp1DE0eWbmBb0mMyDjcKr33+MV72NFjbCME1LlHzVCTyLeChZmqJDGjWucjSPsm+mu2QO6DKDZDtQ9hhDJYWPVFLmpDVsC%7Ctkp%3ABFBM5rHbvt1k' and (text() = 'EXCELLENT Apple MacBook Air 11 INTEL CORE i5 SSD Mac OSOpens in a new window or tab' or . = 'EXCELLENT Apple MacBook Air 11 INTEL CORE i5 SSD Mac OSOpens in a new window or tab')]</value>
      <webElementGuid>0fe3d269-db54-4206-a8e2-c9531ede0266</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
